baseURL = "https://snowfla.com/"
languageCode = "en-us"
title = "snowflake, kafka, and other silly adventures"
theme = "ananke"

copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License."

enableemoji = true

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "favicon.ico"
  site_logo = ""
  description = "description lang here"
  facebook = ""
  twitter = "https://twitter.com/ahnj"
  instagram = ""
  youtube = ""
  github = "https://github.com/ahnj"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/jimahn"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/Bubo_scandiacus_male_Muskegon.jpg"
  recent_posts_number = 1

  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="noopener">CC BY-NC-SA 4.0</a>'

